osm-db:
  container_name: osm-db
  image: nanook/stonemason-droid-base:0.3.0
  entrypoint: /bin/bash
  command: ./docker-init.sh
  environment: &envs
    PGHOST: 172.26.183.193
    PGPORT: 5432
    PGUSER: postgres
    PGDATABASE: stonemason_osm
    PGPASSWORD: 123456

osm-data:
  container_name: osm-data
  image: nanook/stonemason-droid-base:0.3.0
  entrypoint: /bin/bash
  command: /tmp/docker-run.sh
  environment:
    <<: *envs
  volumes:
    - ./:/tmp/